apiVersion: v1
kind: Secret
metadata:
  name: taskflow-secrets
  namespace: taskflow
type: Opaque
stringData:
  postgres-password: "yourpassword"
  connection-string: "Host=taskflow-postgres;Port=5432;Database=taskflow;Username=postgres;Password=yourpassword"